I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/woman_history.rpy", line 11, in script
    if skin == '':
  File "game/woman_history.rpy", line 11, in <module>
    if skin == '':
NameError: name 'skin' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/woman_history.rpy", line 11, in script
    if skin == '':
  File "C:\Users\Пользователь\Desktop\renpy-8.3.2-sdk\renpy\ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Пользователь\Desktop\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Пользователь\Desktop\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/woman_history.rpy", line 11, in <module>
    if skin == '':
NameError: name 'skin' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
Название новеллы 1.0
Mon Nov 18 18:31:17 2024
